system:
  port: 8889

mysql:
  port: "3306"
  config: charset=utf8mb4&parseTime=True&loc=Local
  db-name: demo
  username: root
  password: "123456"
  path: 172.16.14.192
  max-idle-conns: 10
  max-open-conns: 100

logger:
  level: debug
  filename: server.log
  max_size: 200
  max_age: 7
  max_backups: 10